package it.csi.movies.model;
// Generated 14-gen-2009 11.36.57 by Hibernate Tools 3.2.2.GA

import it.csi.movies.model.enums.Storage;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Support generated by hbm2java
 */
@Entity
@Table(name = "support", catalog = "movies")
public class Support implements java.io.Serializable {

	private Integer id;
	private Integer folder;
	private Integer posNumber;
	private Storage storage;
	private String borrowedTo;
	private Set<Movie> movies = new HashSet<Movie>(0);

	public Support() {
	}

	public Support(Integer folder, Integer posNumber, Storage storage,
			String borrowedTo, Set<Movie> movies) {
		this.folder = folder;
		this.posNumber = posNumber;
		this.storage = storage;
		this.borrowedTo = borrowedTo;
		this.movies = movies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "folder")
	public Integer getFolder() {
		return this.folder;
	}

	public void setFolder(Integer folder) {
		this.folder = folder;
	}

	@Column(name = "pos_number")
	public Integer getPosNumber() {
		return this.posNumber;
	}

	public void setPosNumber(Integer posNumber) {
		this.posNumber = posNumber;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "storage")
	public Storage getStorage() {
		return this.storage;
	}

	public void setStorage(Storage storage) {
		this.storage = storage;
	}

	@Column(name = "borrowed_to")
	public String getBorrowedTo() {
		return this.borrowedTo;
	}

	public void setBorrowedTo(String borrowedTo) {
		this.borrowedTo = borrowedTo;
	}

	@OneToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH}, fetch = FetchType.LAZY, mappedBy = "support")
	public Set<Movie> getMovies() {
		return this.movies;
	}

	public void setMovies(Set<Movie> movies) {
		this.movies = movies;
	}

}
